import Head from 'next/head'
import CircleBarComponent from "../components/charts/circleBar.component";
import InputComponent from "../components/input/input.component";

const Home = () => {

    return (
        <>
            <Head>
                <title>erdts - Beta</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <CircleBarComponent title={"Title"} content={"data datatype"} percent={69}/>
                <InputComponent placeholder={"SessionID"} onSubmit={ (msg:string)=> {console.log(msg)} }/>
                <InputComponent placeholder={"SessionID"} onSubmit={ (msg:string)=> {console.log("Msg Submitted:" + msg)} }/>

            </main>
        </>
    )
}

export default Home
