import Head from 'next/head'
import CircleBarComponent from "../components/charts/circleBar.component";

const Home = () => {

    return (
        <>
            <Head>
                <title>erdts - Beta</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <CircleBarComponent title={"Title"} content={"data datatype"} percent={69}/>
            </main>
        </>
    )
}

export default Home
