import Head from 'next/head'
import PanelComponent from "../components/panel/panel.component";


const Home = () => {

    return (
        <>
            <Head>
                <title>erdts - Beta</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>

                <PanelComponent></PanelComponent>

            </main>
        </>
    )
}

export default Home
